### ISSUE TITLE
Explicit construction of the submonoid generated by a subset Remark 15 p. 7 is wrong

### ISSUE THREAD

**Issue by eric-downes** [ralphS16/MyFirstBook#1]
Hi.  You wrote for S ⊆ M, where (M, *, 1_M) is a monoid

〈 S 〉 = { x1 * x2 * ... * xn | n ∈ ℕ, x1, x2, ... ∈ S ∪ {1_M} }

I believe this is wrong.  Consider the monoid (ℕ, +, 0) = 〈 1 〉 
By the construction provided there are only sums of two elements, so

〈 1 〉 = {0,1,2}

we need to be able to iterate.

You could say instead something like

{x1 ^k(x1) * x2 ^k(x2) * ... * xn ^k(xn) | n ∈ ℕ; x1, x2, ... ∈ S ∪ {1_M}; ∀ k: S --> ℕ}

But generally a completely explicit construction of any arbitrary finitely-generated monoid is not possible.  If it were I believe the word problem would be decidable.

**Comment by ralphS16** [comment]
I am not sure I completely understood your comment. Thanks for making it.

First, are you talking about this part?:
![image](https://github.com/ralphS16/MyFirstBook/assets/20562829/c182cc7e-f10e-43a7-bce3-3a9831be7815)

Second, if I want to write 3, I would write 1+1+1, why doesn't this work? Nothing says that x_1 and x_2 have to be different. Wikipedia says the following:
![image](https://github.com/ralphS16/MyFirstBook/assets/20562829/d66d7eb9-9379-457b-b620-c31964c30924)
This is almost what I wrote because I made the mistake of not allowing inverses (I was maybe thinking of generating a submonoid as you were writing), so I should write x_1 \cdots x_n where x_i \in S \cup S^{-1} with the evident definition of S^{-1}. Is there something I am missing?

Third, I do not think your link with the word problem is correct here. The word problem is interesting when (finitely) generating a monoid/group with symbols that do not already live inside another group. So if I write C_n = < x | x^p = 1>, the x^p is really a formal expression that contains p x's put together, and in order to verify if x^n = x^m, I need to solve an (easy) instance of the word problem. When I write x_1 \cdots x_n, I do not mean the formal expression but the actual value of this expression inside the group G where S lives, so verifying whether x_1x_2 = x_2x_2 is done automatically by the computation inside G.

What do you think?

**Comment by eric-downes** [comment]
I think I was confused.

You mean x1, x2, ... to be *possibly indistinct* members of S, in which case I have no objection; as you say x1 = 1 = x2 = x3 allows you to reach 3.

Indeed.  This is actually what you wrote!  My apologies!  Somehow I misread the index to be over the generating set, when clearly you mean the subscript to be an arbitrary function {1, ... |S|} --> S which need not be injective.

As far as generating groups, yeah the angle brackets get abused in standard practice, and clearly mean something different in the case of generating groups vs monoids.  As you said, we would draw x_i from S ∪ S⁻¹ ∪ {1_G} if we want the angle brackets to mean a uniform closure operator, independent of wether we are working in Grp, Mon, etc.

Partially-agreed on the third point; certainly the word problem has a *clearer* meaning when inside an already defined group/monoid.  But I think in addition to being e.g. a subgroup of a known group, that the subgroup whose presentation we are expanding needs to be [residually finite](
https://en.wikipedia.org/wiki/Residually_finite_group) for that argument to work? 

Regardless, that is entirely beside the point!  What you wrote in the text is fine, and I was wrong, and hereby withdraw my complaint.  Thank you!
